[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

#[programs.localnet]
#marscorp_chain = "9gdAh93PkXA2GnoZisdq9fXxfgzWz4r5ZPpqjdj6Wy8P"
marscorp_exchange = "5GKfHwujgiKLXP84f28HyGL5FJ3AnunKsVGmKDmG6RXi"

[programs.devnet]
#marscorp_chain = "9gdAh93PkXA2GnoZisdq9fXxfgzWz4r5ZPpqjdj6Wy8P"
marscorp_exchange = "5GKfHwujgiKLXP84f28HyGL5FJ3AnunKsVGmKDmG6RXi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = 'C:\\Users\\ezevi\\.config\\solana\\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
